# Generated by Django 4.2.7 on 2023-11-01 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_remove_district_city_city_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='district',
        ),
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='test_app.city'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='test_app.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='test_app.district')),
            ],
        ),
    ]
